<a href="https://colab.research.google.com/github/mansichug-h/big-data/blob/main/Labeval_group2_202301033.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1
import numpy as np
arr1= np.array([10,52,62,16,16,54,453])
print(np.sort(arr1))

[ 10  16  16  52  54  62 453]


In [4]:
#2
import numpy as np
arr1= np.array([10,52,62,16,16,54,453])
print(np.sort(arr1))
indices = np.argsort(arr1)
print(indices)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]


In [6]:
#3
import numpy as np
arr1= np.array([10,52,62,16,16,54,453])
print(arr1)
k = 4 #value declare no of smallest elemets
arr2 = np.sort(arr1)
print(k, "smallest elements of the array")
print(arr2[:k])




[ 10  52  62  16  16  54 453]
4 smallest elements of the array
[10 16 16 52]


In [8]:
import numpy as np
arr1= np.array([10,52,62,16,16,54,453])
st_arr =np.sort(arr1);
ut_arr =np.unique(st_arr)
print(st_arr[-5:])



[ 16  52  54  62 453]
